FROM node:12-buster-slim AS builder

# Declaring env
ENV NODE_ENV development

WORKDIR /amato
COPY . .

RUN apt-get update
RUN apt-get -y install curl
RUN npm install -g n
RUN n prune
RUN n 18.16.1

FROM node:12-buster-slim

RUN apt-get update
RUN apt-get -y install curl
RUN npm install -g n
RUN n prune
RUN n 18.16.1
USER 1000
WORKDIR /amato
COPY --from=builder /amato .
EXPOSE 3000
CMD ["node", "app.js"]